CREATE DATABASE IF NOT EXISTS nexus;
USE nexus;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pseudo VARCHAR(50) NOT NULL,
    mdp VARCHAR(255) NOT NULL,
    date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    auteur VARCHAR(50) NOT NULL,
    titre VARCHAR(100) NOT NULL,
    contenu TEXT NOT NULL,
    image VARCHAR(255) DEFAULT '',
    date_creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    likes INT DEFAULT 0
);

CREATE TABLE likes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    post_id INT NOT NULL,
    pseudo VARCHAR(50) NOT NULL
);

CREATE TABLE commentaires (
    id INT AUTO_INCREMENT PRIMARY KEY,
    post_id INT NOT NULL,
    auteur VARCHAR(50) NOT NULL,
    texte TEXT NOT NULL,
    date_creation DATETIME DEFAULT CURRENT_TIMESTAMP
);
